# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: expense
#   region: us-east-1

# managedNodeGroups:
#   - name: expense
#     instanceType: m5.large
#     desiredCapacity: 3
#     spot: true
#     # availabilityZones:
#     # - us-east-1f




apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense-cluster
  region: us-east-1
  # tags:
  #   project: expense
  #   environment: dev
  #   created_by: HemanthKumar

managedNodeGroups:
  - name: expense
    instanceType: m5.large
    # minSize: 1
    # maxSize: 10
    desiredCapacity: 3
    spot: true